pipeline {
    agent any
    environment {
        GIT_REPOSITORY = "git@github.com:pggomez1989/todo-list-devops.git"
        BRANCH_PROJECT = "main"
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key') 
    }
    parameters {
        booleanParam(name: 'DESTROY_INFRA', defaultValue: false, description: 'Set to true to destroy the infrastructure')
    }
    stages {
        // stage('Build start') {
        //     steps {
        //         git branch: "${BRANCH_PROJECT}",
        //             credentialsId: '7df94e06-bbc2-4332-83e5-dfac02b22fd6',
        //             url: "${GIT_REPOSITORY}"
        //     }
        // }
        stage('Setup Terraform') {
            steps {
                dir('infrastructure/terraform') {
                    script {
                        // Verifica la versión de Terraform
                        sh 'terraform --version'
                        
                        // Inicializa Terraform
                        def tfInitStatus = sh(script: 'terraform init', returnStatus: true)
                        
                        // Verifica el resultado de la inicialización de Terraform
                        if (tfInitStatus == 0) {
                            echo 'Terraform initialized successfully.'
                        } else {
                            error 'Failed to initialize Terraform.'
                        }
                    }
                }
            }
        }
        stage('Apply Terraform') {
            when {
                expression { return !params.DESTROY_INFRA }
            }
            steps {
                dir('infrastructure/terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
        stage('Destroy Terraform') {
            when {
                expression { return params.DESTROY_INFRA }
            }
            steps {
                dir('infrastructure/terraform') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
        stage('Obtain Instance IP') {
            steps {
                script {
                    dir('infrastructure/terraform') {
                        def instance_ip = sh(script: 'terraform output -raw instance_ip', returnStdout: true).trim()
                        echo "Instance IP: ${instance_ip}"
                        if (!instance_ip) {
                            error "Failed to obtain instance IP from Terraform output"
                        }
                        env.INSTANCE_IP = instance_ip
                    }
                }
            }
        }
        stage('Prepare EC2 Instance') {
            steps {
                script {
                    sshagent(credentials: ['my-ssh-key']) {
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${env.INSTANCE_IP} 'mkdir -p /home/ubuntu/application'"
                    }
                }
            }
        }
        stage('Transfer Application Files') {
            steps {
                script {
                    sshagent(credentials: ['my-ssh-key']) {
                        sh "scp -o StrictHostKeyChecking=no -r app/* ubuntu@${env.INSTANCE_IP}:/home/ubuntu/application/"
                    }
                }
            }
        }
        stage('Deploy Docker Compose') {
            steps {
                script {
                    sshagent(credentials: ['my-ssh-key']) {
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${env.INSTANCE_IP} 'cd /home/ubuntu/application && docker-compose up -d'"
                    }
                }
            }
        }
    }
}
