version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: user_todos
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - miapp-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  miapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: user_todos
      MYSQL_PASSWORD: user_password
      MYSQL_DB: todos
    networks:
      - miapp-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - miapp-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    networks:
      - miapp-net

networks:
  miapp-net:
    driver: bridge

volumes:
  mysql-data:
  grafana-storage:
