{
 "title": "Todo List",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu_usage_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cpu_usage_percentage{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "memory_usage_bytes{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(requests_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds_count{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_microseconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds_sum{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}